### PR TITLE
Album tagging fix

### PR DESCRIPTION
**Pull request by jsaddiction**
An even more edge case was noticed when an album processed by beets doesn't quite match Lidarr. This only happens when multiple releases are identified by beets and the wrong one (from Lidarr's perspective) is selected.  The result in this case is two similarly named albums within the same artist.

### CODE REVIEW

**Comment by RandomNinjaAtk** [comment]
Actually probably don't want to do this, because it could be possible that you matched an album that doesn't match the same release group, and forcing it to be the same would cause you to import data incorrectly.

**Comment by jsaddiction** [comment]
Not sure I understand exactly what you mean. I realize that an album may have several releases and that the downloaded tracks may come from those different release groups.

The problem I am trying to solve is where an artist would have 2 or more listings of the same album in kodi. Upon further investigation I noticed that the two albums have different album ids.

To Me, even if the album id is forced to be consistent with lidarr's understanding of the album construct then the appearance in kodi would also be commensurate with lidarr.

Does lidarr change a release upon import to match the tracks it's found? If so then I see your point and then it should be up to lidarr to tag with the appropriate album id and release id after it's made that decision

**Comment by RandomNinjaAtk** [comment]
Lidarr uses the tags to match an album for import. So changing the tags could result undesirable import results by making lidarr think its a different album than it really is...

**Comment by jsaddiction** [comment]
I do have lidarr set where it doesn't mess with tags. This was in attempt to get beets to process tags more to my liking, ie. genre whitelist. Lidarr doesn't seem to have a method for limiting which tags are written. Seems I'm at a stalemate with that functionality unless you have any ideas.

**Comment by RandomNinjaAtk** [comment]
You should have lidarr tag and use the post processing script to re-process with beets.

That's what I do anyways.

**Pull request closed without merging**
